---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.haml"
  - "**.rb"
  - "**.rhtml"
  - "**.slim"
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
exclude_paths:
- config/
- db/
- spec/
- vendor/
- app/interactors/
- app/api/
- app/assets/javascripts/legacy/
- app/assets/javascripts/legacy_application.js
- app/assets/legacy_templates/
- app/assets/stylesheets/legacy/
- app/assets/stylesheets/legacy_application.scss
- app/controllers/legacy_controller.rb
- app/views/legacy/
- app/models/abilities/
- app/models/observers/
- app/models/media_types/
- app/models/post_types/
- app/models/onet/
- app/models/concerns/searchable*
- app/models/application.rb
- app/models/author.rb
- app/models/bulk_job.rb
- app/models/category.rb
- app/models/document.rb
- app/models/locale.rb
- app/models/localization.rb
- app/models/media.rb
- app/models/onet.rb
- app/models/post.rb
- app/models/snippet.rb
- app/models/webpage.rb
- app/jobs/bulk_create_media_job.rb
- app/jobs/bulk_create_users_job.rb
- app/jobs/cache_bust_webpage_job.rb
- app/jobs/youtube_media_job.rb
- app/jobs/youtube_media_job.rb
- lib/tasks/cortex.rake
