const TOGGLE_TENANT_SWITCHER = 'TOGGLE_TENANT_SWITCHER'
const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
const SELECT_TENANT = 'SELECT_TENANT'
const TENANT_UPDATED = 'TENANT_UPDATED'
const TENANT_UPDATE_ERROR = 'TENANT_UPDATE_ERROR'
const SUBLIST_CLICKED = 'SUBLIST_CLICKED'
const PAGINATE_BACK = 'PAGINATE_BACK'

export {
  TOGGLE_TENANT_SWITCHER,
  SELECT_TENANT,
  TENANT_UPDATED,
  SUBLIST_CLICKED,
  TENANT_UPDATE_ERROR,
  TOGGLE_SIDEBAR,
  PAGINATE_BACK
}
