const TOGGLE_TENANT_SWITCHER = 'TOGGLE_TENANT_SWITCHER'
const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
const SELECT_TENANT = 'SELECT_TENANT'

export {
  TOGGLE_TENANT_SWITCHER,
  SELECT_TENANT,
  TOGGLE_SIDEBAR
}
