const TOGGLE_TENANT_SWITCHER = 'TOGGLE_TENANT_SWITCHER'
const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
const SELECT_TENANT = 'SELECT_TENANT'
const TENANT_UPDATED = 'TENANT_UPDATED'
const TENANT_UPDATE_ERROR = 'TENANT_UPDATE_ERROR'

export {
  TOGGLE_TENANT_SWITCHER,
  SELECT_TENANT,
  TENANT_UPDATED,
  TENANT_UPDATE_ERROR,
  TOGGLE_SIDEBAR
}
