
const NEXT_STEP = 'NEXT_STEP'
const PREVIOUS_STEP = 'PREVIOUS_STEP'
const FORM_VALID = 'FORM_VALID'
const STEP_CLICKED = 'STEP_CLICKED'
const FORM_INVALID = 'FORM_INVALID'
const DISPLAY_VALIDATIONS = 'DISPLAY_VALIDATIONS'
const CONTENT_TYPE_UPDATED = 'CONTENT_TYPE_UPDATED'

export {
  NEXT_STEP,
  PREVIOUS_STEP,
  FORM_VALID,
  STEP_CLICKED,
  FORM_INVALID,
  CONTENT_TYPE_UPDATED,
  DISPLAY_VALIDATIONS
}
