const ADD_FIELD = 'ADD_FIELD'
const CLOSE_ADD_FIELD = 'CLOSE_ADD_FIELD'
const UPDATE_FIELD = 'UPDATE_FIELD'
const NEXT_STEP = 'NEXT_STEP'
const PREVIOUS_STEP = 'PREVIOUS_STEP'
const FORM_VALID = 'FORM_VALID'
const STEP_CLICKED = 'STEP_CLICKED'
const FORM_INVALID = 'FORM_INVALID'
const DISPLAY_VALIDATIONS = 'DISPLAY_VALIDATIONS'
const CONTENT_TYPE_UPDATED = 'CONTENT_TYPE_UPDATED'
const OPEN_FIELD_EDITOR =  'OPEN_FIELD_EDITOR'
const CLOSE_FIELD_EDITOR = 'CLOSE_FIELD_EDITOR'
const EXPAND_DEFAULTS = 'EXPAND_DEFAULTS'
const UPDATE_FIELD_FORM = 'UPDATE_FIELD_FORM'
const OPEN_FIELD_FORM = 'OPEN_FIELD_FORM'
const FIELD_NAME_ERROR = 'FIELD_NAME_ERROR'
const EDIT_FIELD = 'EDIT_FIELD'
const DELETE_FIELD = 'DELETE_FIELD'
const UPDATE_YAML_FIELD = 'UPDATE_YAML_FIELD'
const UPDATE_STEP = 'UPDATE_STEP'
const DB_SYNCING = 'DB_SYNCING'
const CONTENT_TYPE_SYNCED = 'CONTENT_TYPE_SYNCED'
const ADD_WIZARD_STEP = 'ADD_WIZARD_STEP'
const WIZARD_STEP_UPDATE = 'WIZARD_STEP_UPDATE'
const WIZARD_SYNCED = 'WIZARD_SYNCED'
const INDEX_SYNCED = 'INDEX_SYNCED'
const RSS_SYNCED = 'RSS_SYNCED'

export {
  DB_SYNCING,
  UPDATE_FIELD,
  WIZARD_SYNCED,
  INDEX_SYNCED,
  RSS_SYNCED,
  ADD_FIELD,
  EDIT_FIELD,
  UPDATE_STEP,
  DELETE_FIELD,
  NEXT_STEP,
  PREVIOUS_STEP,
  FORM_VALID,
  STEP_CLICKED,
  FORM_INVALID,
  WIZARD_STEP_UPDATE,
  CONTENT_TYPE_SYNCED,
  CONTENT_TYPE_UPDATED,
  DISPLAY_VALIDATIONS,
  OPEN_FIELD_EDITOR,
  CLOSE_FIELD_EDITOR,
  CLOSE_ADD_FIELD,
  EXPAND_DEFAULTS,
  UPDATE_FIELD_FORM,
  OPEN_FIELD_FORM,
  ADD_WIZARD_STEP,
  UPDATE_YAML_FIELD,
  FIELD_NAME_ERROR
}
