const ADD_FIELD = 'ADD_FIELD'
const CLOSE_ADD_FIELD = 'CLOSE_ADD_FIELD'
const UPDATE_FIELD = 'UPDATE_FIELD'
const NEXT_STEP = 'NEXT_STEP'
const PREVIOUS_STEP = 'PREVIOUS_STEP'
const FORM_VALID = 'FORM_VALID'
const STEP_CLICKED = 'STEP_CLICKED'
const FORM_INVALID = 'FORM_INVALID'
const DISPLAY_VALIDATIONS = 'DISPLAY_VALIDATIONS'
const CONTENT_TYPE_UPDATED = 'CONTENT_TYPE_UPDATED'
const OPEN_FIELD_EDITOR =  'OPEN_FIELD_EDITOR'
const CLOSE_FIELD_EDITOR = 'CLOSE_FIELD_EDITOR'
const EXPAND_DEFAULTS = 'EXPAND_DEFAULTS'
const UPDATE_FIELD_FORM = 'UPDATE_FIELD_FORM'
const OPEN_FIELD_FORM = 'OPEN_FIELD_FORM'
const FIELD_NAME_ERROR = 'FIELD_NAME_ERROR'
const EDIT_FIELD = 'EDIT_FIELD'
const DELETE_FIELD = 'DELETE_FIELD'
const UPDATE_YAML_FIELD = 'UPDATE_YAML_FIELD'
const OPEN_STEP_FORM = 'OPEN_STEP_FORM'
const UPDATE_STEP = 'UPDATE_STEP'

export {
  UPDATE_FIELD,
  ADD_FIELD,
  EDIT_FIELD,
  UPDATE_STEP,
  DELETE_FIELD,
  NEXT_STEP,
  PREVIOUS_STEP,
  FORM_VALID,
  STEP_CLICKED,
  FORM_INVALID,
  CONTENT_TYPE_UPDATED,
  DISPLAY_VALIDATIONS,
  OPEN_FIELD_EDITOR,
  CLOSE_FIELD_EDITOR,
  CLOSE_ADD_FIELD,
  EXPAND_DEFAULTS,
  UPDATE_FIELD_FORM,
  OPEN_FIELD_FORM,
  OPEN_STEP_FORM,
  UPDATE_YAML_FIELD,
  FIELD_NAME_ERROR
}
